### ISSUE TITLE
Promises outcomes are mixed up.

### ISSUE THREAD

**Issue by vcarel** [reflux/reflux-promise#14]
Maybe I didn't understand the purpose of this lib, but I think there is something wrong in the way it manages Promises.

When an action is triggered, the returned Promise object should be _resolved_ or *rejected" according to the outcome of the triggered action.

The point is that RefluxPromise completly ignores Promised objects returned by an action handler. Instead, it creates its own Promise which is resolved / rejected whenever the `completed` / `failed` methods of the action are called. At anytime.

In otherwords, when an action is called, it does not return _a promise of the outcome_ of this action, but a promise of the outcome of _any similar_ action.

For instance...

I'm using a Reflux store to persist changes on DB using a REST service. If the service fails (for whatever reason), I want to know which action couldn't make it. That's why I wanted to used Promises.

So I would like to do the following:

```
var actions = {
    'change': Reflux.createAction({ asyncResult: true })
};

Reflux.createStore({
    listenables: actions,

    onChange: function(data) {
        return RestPromises.jsonPost('/my_service', data)
    },
})

changePromise = actions.change({foo: 'bar'});
```

But it doesn't work ! `changePromise` is not the Promise returned by `jsonPost`, but a Promise created by Reflux-Promise which is actually always resolved.

So I had to do the following instead: 

```
var actions = {
    'change': Reflux.createAction({ asyncResult: true })
};

Reflux.createStore({
    listenables: actions,

    onChange: function(data) {
        return RestPromises.jsonPost('/my_service', data)
            .then(function () {
                actions.change.completed();
            })
            .catch(function (error) {
                actions.change.failed(error);
            });
    },
})
```

But then, when I trigger the same action 2 times...

```
changePromise_1 = actions.change({foo: 'good'});
changePromise_2 = actions.change('bad');
```

... they will get the same outcome, and will be both rejected or resolved ! Obviously this is not a desired behavior.

**Comment by devinivy** [comment]
It sure isn't desired!  I'll make a point to look into this.  Do you happen to have time to write a failing test?

**Comment by vcarel** [comment]
Hi, sorry to reply late... I don't have time to write a failing test.
Do you confirm the point BTW ?

**Comment by suem** [comment]
Hi, I noticed a similar problem that can be reproduced on nodejs with the following code:

```
var Reflux = require('reflux')
var RefluxPromise = require('reflux-promise')
Reflux.use(RefluxPromise(Promise));

var actions = Reflux.createActions({
    load: {asyncResult: true},
});

var store = Reflux.createStore({

    listenables: [actions],

    onLoad: function(x) {
        actions.load.promise(Promise.resolve(x));
    }

});

actions.load(1).then(x => {
    console.log('completed load: ' + x);
});

actions.load(2).then(x => {
    console.log('completed load: ' + x);
});

```

The output is:

> completed load: 1
> completed load: 1 

instead of 

> completed load: 1
> completed load: 2

**Comment by BryanGrezeszak** [comment]
This issue is a misunderstanding of flux itself. It's absolutely intended that the store's `onChange` return would not be what the returned promise from the action is. There could be 100+ stores all listening to that action! Which one would be the right one to get the return value from?

Data flows from the actions to the stores, not the other way around. That is the fundamental concept of 1-way flow of data.

Promises themselves being returned from an action call don't necessarily violate that principal, because it's only data about the action call itself that the promise is reflecting. So, while using them doesn't necessarily move you forward in that 1 way flow, it doesn't move you backward either. But trying to get data from the store that's listening for the action backward into the promise returned by the action would break the entire concept of flux.
